### PR TITLE
QA on closing-wg.html

### PR DESCRIPTION
**Pull request by koalie**

### CODE REVIEW

**Review by csarven — APPROVED** [review]
I'd like to understand for future reference/use: why is "work Group" more appropriate than "Working Group" here?

**Comment by koalie** [comment]
> I'd like to understand for future reference/use: why is "work Group" more appropriate than "Working Group" here?

It’s generic and thus encompasses both Working and Interest Groups which are the groups currently chartered through the Process.

**Comment by csarven** [comment]
Thanks, that makes sense. Noting now that the intention of the PR is to cover the IG as well. I originally interpreted the heading and the URL (including "wg" for Working Group as opposed to work Group)

**Comment by koalie** [comment]
> Thanks, that makes sense. Noting now that the intention of the PR is to cover the IG as well. I originally interpreted the heading and the URL (including "wg" for Working Group as opposed to work Group)

Oh it was probably intended as the acronym for working group! After all the repartition between the two types is 40 or 50 to 10, so it’s easy to overlook interest groups.

**Pull request merged**
