### PR TITLE
Remove participant directory as this section was marked as deprecated

### PR DESCRIPTION
**Pull request by vivienlacourba**

### CODE REVIEW

**Comment by vivienlacourba** [comment]
@plehegar do you think we need to set up redirects for:
https://www.w3.org/Guide/participant/group.html

**Comment by plehegar** [comment]
groups.html used to be advertised by our [onboarding emails](https://github.com/w3c/onboarding/commit/77f726f69b8f549f40641c619b73c568fa8e72eb). Setting a redirect would be nice.

I don't think we used resources.html at the end.

**Review by plehegar — APPROVED** [review]
modulo the redirect.

**Comment by vivienlacourba** [comment]
> groups.html used to be advertised by our [onboarding emails](https://github.com/w3c/onboarding/commit/77f726f69b8f549f40641c619b73c568fa8e72eb). Setting a redirect would be nice.

Redirected added in af6c53d4c4593fdc04558500dbc88e5c9ecfb70e

**Pull request merged**
