### PR TITLE
Add a link to w3c/strategy when doing AC reviews

### PR DESCRIPTION
**Pull request by plehegar**
Following a conversation on slack with @npdoty , it would good to point the AC to the pre-AC review of the charter

### CODE REVIEW

**Comment by plehegar** [comment]
@koalie , please see also our [template](https://www.w3.org/Team/Templates/cfr.html) (Team-Only).

**Comment by plehegar** [comment]
oh, and maybe https://www.w3.org/2002/09/wbs/33280/apCFRFactory needs to be modified but not sure how to do this.

**Comment by koalie** [comment]
> oh, and maybe https://www.w3.org/2002/09/wbs/33280/apCFRFactory needs to be modified but not sure how to do this.

I've [asked](https://lists.w3.org/Archives/Team/sysreq/2023Mar/0133.html) the Systeam to make the change.

**Comment by koalie** [comment]
I'm sorry I was not notified about this pull request, I'm going to make some further QA changes directly.

**Pull request merged**
